title: HYPΣR ✦⁺
description: positive summer 
baseurl: ""
url: "https://hyperlabel.co"

permalink: /:slug

favicon: "favicon.png"

# Build settings
remote_theme: 0xigami/no-style-please

theme_config:
  appearance: "auto"
  back_home_text: "home" 
  date_format: "%Y-%m-%d" 
  show_description: true 

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
